//5
// Automatically generated code. Any changes will be lost!
 // This code was generated by a tool. Any changes made manually will be lost
 // the next time this code is regenerated.
 // 
  
 using System.Reflection;

[assembly: AssemblyVersion("1.3.3.7")]
[assembly: AssemblyFileVersion("1.3.2.5")]
[assembly: AssemblyInformationalVersionAttribute("Biomatic 1.3.2.5 -zed'K BETA")]
//"@FULL_VERSION@"

namespace Biomatic
{
    public static class Version
    {
        public const int major = 1;
        public const int minor = 3;
        public const int patch = 3;
        public const int build = 7;
        public const string Number = "1.3.3.7";
#if DEBUG
        public const string Text = Number + " -zed'K BETA DEBUG";
#else
        public const string Text = Number + " -zed'K BETA";
#endif
    }
}